#!/bin/zsh

if [ ! -d "$DIRECTORY" ]; then
	mkdir bin
	echo "Creating bin directory."
else
	echo "Bin directory exists."
fi

gcc -Wall -pedantic $(pkg-config --cflags gtk4) -Og -o ./bin/"$1" "$1".c $(pkg-config --libs gtk4)
if [ $? -ne 0 ]; then
	echo "Compile failed!"
	exit 1
else
	./bin/"$1"
fi
